[package]
name = "network_scanner"
version = "0.1.0"
authors = ["P Deepanshu"]
edition = "2021"
repository = "https://github.com/deep60/network_scanner"
license = "MIT"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
pcap = "1.1.0"
pnet = "0.35.0"
dirs = "5.0.1"
